import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs';
import { AiFillTwitterCircle,
        AiFillLinkedin} from 'react-icons/ai';
import Image from "next/image";
import deved from "../public/IMG.jpg";
import design from "../public/design.png";
import code from   "../public/code.png";

import { useState } from 'react';


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Lonwabo Alvin Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900"> 
        <section className=" min-h-screen">
        <nav className="py-10 mb-12 flex justify-between">
          <h1 className="text-xl">Portfolio</h1>
          <ul className="flex items-center">
            <li>
            <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}
            className="cursor-pointer text-2xl"/>
            </li>
            <li> <a className=" bg-gradient-to-r from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8">
              Resume</a></li>
          </ul>
        </nav>
        <div className="text-center p-10">
          <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
            Lonwabo Alvin</h2>
          <h3 className="text-2xl py-2 md:text-3xl dark:text-gray-200"> Junior Software Developer</h3>
          <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">
            <div>
                  I am a Software Developer from the Cape Peninsula University of Technology 
                  with a total of 4 years of educational and industry background in Java software
                  design, development, and testing. Seeking an opportunity to utilize broad 
                  educational background with excellent analytical, technical, and programming
                  skills to thrive as an entry- level Software developer. To make use of industry
                  experience obtained as an entry level.
           </div>
          </p>
        </div>
        <div>
            <h3 className="text-center text-3xl py-3 dark:text-gray-200">Why SovTech? </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200">
            The reason I want to join SovTech is because I believe in SovTech values.
            It is a company that I beileve will be suitable for me because I believe 
            in their vision. SovTech is one the most growing companies in Africa. I beileve
            should I be given the opportunity I will be be able to learn and grow in the
            Tech industry by having mentors. I believe the SovTech graduates programme will
            play a magnificant role in my career.
          </p>

            
          </div>
        <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
          <AiFillTwitterCircle />
          <AiFillLinkedin />
        </div>

        <div className="relative mx-auto bg-gradient-to-b from teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
        <Image src={deved} layout="fill" objectFit="cover" />
        </div>
          
        </section>
        <div>
          <p>
          <h3 className="text-3xl py-1 dark:text-white ">Skills and Technologies</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a software developer student, I have
              learnt different programming tools and Technologies. I have collaborated in 
              many tech projects.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I have worked with these various rage of tools and technologies as mentioned
              below:
            </p> 
          </p>
        </div>
        <div className="lg:flex gap-10" >
          <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
          <Image src={design} width={100} height={100} />
          <h4 className="text-lg font-medium pt-8 pb-2  ">
          Beautiful Designs  
            </h4>
            <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              <h5 className="py-4 text-teal-600">Design Tools I Use</h5>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Illustrator</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
          </div>
          <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Design and development tools used
                
              </p>
              <h4 className="py-4 text-teal-600">Front-end Tech languages I Use</h4>
              <p className="text-gray-800 py-1">HTML CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">ReactJS</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Design and Development tools and technologies used.
              </p>
              <h4 className="py-4 text-teal-600">Back-End Technologies I Use</h4>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">Springboot</p>
              <p className="text-gray-800 py-1">Hibernate</p>
            </div>
          
        </div>
        
       
      </main>
      
    </div>
  )
}
